save_data: ./example

# Corpus opts:
data:
    finnish:
        path_src: ./train.bpe.fi
        path_tgt: ./train.bpe.en
        weight: 1
    valid:
        path_src: ./val.bpe.fi
        path_tgt: ./val.bpe.en


## Where the vocab(s) will be written
src_vocab:  ./vocab.fi.src #update
tgt_vocab: ./vocab.en.tgt #update

# General opts
save_model: ./model-finetune
train_from: model-fi-en-og-transformer_step_150000.pt 
save_checkpoint_steps: 15000 #need to change
valid_steps: 15000 #need to change
train_steps: 240000 #need to change
early_stopping: 3 #change?
early_stopping_criteria: ppl


# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout: 0.1
attention_dropout: 0.1

# Optimization
model_dtype: fp32
optim: adam
learning_rate: 2
warmup_steps: 8000
decay_method: noam
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: tokens

# Batching
world_size: 1
gpu_ranks: [0]
batch_type: tokens
batch_size: 4096
valid_batch_size: 4096
max_generator_batches: 2
accum_count: 8
