save_data: ./example

# Corpus opts:
data:
    finnish:
        path_src: ./work/train.bpe.fi
        path_tgt: ./work/train.bpe.en
    valid:
        path_src: ./work/val.bpe.fi
        path_tgt: ./work/val.bpe.en

# Where the vocab(s) will be written
src_vocab: ./vocab.fi_en.src
tgt_vocab: ./vocab.fi_en.tgt

# Prevent overwriting existing files in the folder
overwrite: False
